export const GLOBAL_LOADDING = 'GLOBAL_LOADDING'
export const GLOBAL_PROGRESS = 'GLOBAL_PROGRESS'
export const GLOBAL_SHOWMSG = 'GLOBAL_SHOWMSG'
export const GLOBAL_HIDEMSG = 'GLOBAL_HIDEMSG'

export const RECEIVE_COLLECTS = 'RECEIVE_COLLECTS'
export const TAG_COLLECTS = 'TAG_COLLECTS'

export const CHANGE_COLLECT_TAG = 'CHANGE_COLLECT_TAG'

export const POST_COLLECTS = 'POST_COLLECTS'
